remote_theme: hheisig51/theme_hitchens

# site settings
title: CHS BACON
email: chsbacon@gmail.com
description: The "Best All Around Club of Nerds", A STEM Club at Charlottesville High School!
street_address: 1400 Melbourne Road
city: Charlottesville
state: VA
zip_code: 22901
country: United States of America

# socials
socials:
  GitHub: https://github.com/chsbacon
  Instagram: https://www.instagram.com/chsbacon/
  Facebook: https://www.facebook.com/chsbacon/
  
